workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
          # OR for app bundle:
          # flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      # OR for app bundle:
      # - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
